version: '2'

services:
  redis:
    restart: always
    image: redis
    container_name: cache
    expose:
      - 6379

  web:
    restart: "no"
    image: node:12
    #image: node:18
    working_dir: /usr/src/app
    volumes:
        - ./:/usr/src/app
        #- ./logs/:/usr/src/app/logs
    ports:
      - "3001"
    env_file:
      - .env
    environment:
      # mongodb:27017 is a direct reference to the 'mongodb' mongo container
      - REDIS_URL=redis://cache
    links:
      - redis
    command: bash -c "npm install && npm run start"

  lb:
    image: dockercloud/haproxy
    restart: always
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80